# Generated by Django 5.1.1 on 2024-10-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comments_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
