# Generated by Django 5.1.1 on 2024-11-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_tag_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='published_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_at',
            field=models.DateTimeField(default=None, verbose_name='Publish at'),
        ),
    ]
