# Generated by Django 5.1.1 on 2024-11-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_blog_published_at_blog_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_at',
            field=models.DateTimeField(verbose_name='Publish at'),
        ),
    ]
