# Generated by Django 5.1.1 on 2024-11-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blog_publish_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='publish_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publish at'),
        ),
    ]
