# Generated by Django 5.1.1 on 2024-11-26 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_blog_publish_at_blog_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish at'),
        ),
    ]
