# Generated by Django 5.1.1 on 2024-11-26 12:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_rename_published_at_blog_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publish_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='publish at'),
        ),
    ]
