# Generated by Django 5.1.1 on 2025-01-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='publish at'),
        ),
    ]
