# Generated by Django 5.1.1 on 2024-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('B', 'صبحانه'), ('D', 'نوشیدنی'), ('DI', 'شام'), ('L', 'ناهار')], default='D', max_length=10, verbose_name='نوع غذا'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام غذا'),
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(upload_to='foods/', verbose_name='تصویر غذا'),
        ),
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.IntegerField(default=5, verbose_name='امتیاز'),
        ),
    ]
