# Generated by Django 5.1.1 on 2024-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_type_food_alter_food_name_alter_food_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.CharField(choices=[('breakfast', 'صبحانه'), ('drink', 'نوشیدنی'), ('dinner', 'شام'), ('lunch', 'ناهار')], default='D', max_length=10, verbose_name='نوع غذا'),
        ),
    ]
