# Generated by Django 5.1.1 on 2025-01-04 17:04

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='type_food',
        ),
        migrations.AddField(
            model_name='food',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('drinks', 'drinks'), ('dinner', 'dinner'), ('lunch', 'lunch')], max_length=19, null=True),
        ),
    ]
